server:
  port: 8081

logging:
  file:
    path: /var/logs/TacoCloud.log
  level:
    root: info
#    org:
#      hibernate:
#        SQL: debug
#        type:
#          descriptor:
#            sql: trace
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_store?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: dn123456
    username: bookmaster
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false
    show-sql: false

bookstore:
  books:
    images: /Users/gangjeongmu/IdeaProjects/DNBookStore/DNBookStore/src/main/resources/static/images/
  point:
    savingRate: 10
  page-size:
    userOrders: 10
    pointHistories: 10
    mainProducts: 8