server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_store?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: dn123456
    username: bookmaster
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

bookstore:
  books:
    images: /Users/gangjeongmu/Documents/book_store/book_images
  point:
    buying-saving-rate: 10